from typing import Awaitable, Callable, Optional

import asyncio


class AudioSource:
    ...


class Client:
    def __init__(self, *, loop: Optional[asyncio.AbstractEventLoop] = ...): ...
    def event(self, coro: Callable[..., Awaitable[None]]): ...
    async def start(self, token: str, *, bot: bool = ...): ...
    async def logout(self): ...
